# Generated by Django 2.2.3 on 2020-03-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('idCard', models.CharField(max_length=18, verbose_name='身份证号')),
                ('phone1', models.CharField(max_length=20, verbose_name='联系电话1')),
                ('phone2', models.CharField(max_length=20, verbose_name='联系电话2')),
                ('primarySchool', models.CharField(max_length=50, verbose_name='毕业小学')),
                ('juniorSchool', models.CharField(max_length=50, verbose_name='毕业初中')),
                ('testScore1', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='初三上学期期中考成绩')),
                ('testRank1', models.IntegerField(verbose_name='初三上学期期中考年级排名')),
                ('testScore2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='初三上学期期末考成绩')),
                ('testRank2', models.IntegerField(verbose_name='初三上学期期末考年级排名')),
                ('specialty', models.CharField(max_length=200, verbose_name='特长')),
                ('photo', models.ImageField(upload_to='img', verbose_name='照片')),
            ],
        ),
    ]
