# Generated by Django 2.2.3 on 2020-03-12 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20200312_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stud',
            options={'verbose_name': '学生信息', 'verbose_name_plural': '学生信息'},
        ),
        migrations.AlterField(
            model_name='stud',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话2'),
        ),
        migrations.AlterField(
            model_name='stud',
            name='primarySchool',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='毕业小学'),
        ),
        migrations.AlterField(
            model_name='stud',
            name='specialty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='特长'),
        ),
        migrations.AlterField(
            model_name='stud',
            name='testRank1',
            field=models.IntegerField(blank=True, null=True, verbose_name='初三上学期期中考年级排名'),
        ),
        migrations.AlterField(
            model_name='stud',
            name='testRank2',
            field=models.IntegerField(blank=True, null=True, verbose_name='初三上学期期末考年级排名'),
        ),
        migrations.AlterField(
            model_name='stud',
            name='testScore1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='初三上学期期中考成绩'),
        ),
        migrations.AlterField(
            model_name='stud',
            name='testScore2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='初三上学期期末考成绩'),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classRoom', models.CharField(max_length=50, verbose_name='试室号')),
                ('seatNo', models.CharField(max_length=20, verbose_name='座位号')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Student.Stud')),
            ],
            options={
                'verbose_name': '准考证',
                'verbose_name_plural': '准考证',
            },
        ),
    ]
