# Generated by Django 2.2.3 on 2020-03-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20200312_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='stud',
            name='specialty',
        ),
    ]
