# Generated by Django 2.2.3 on 2020-03-12 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_auto_20200312_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img', verbose_name='照片'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stud',
            name='specialty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='特长'),
        ),
    ]
