# Generated by Django 2.2.3 on 2020-03-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_auto_20200312_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud',
            name='specialty',
        ),
    ]
