# Generated by Django 2.2.3 on 2020-03-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_remove_stud_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud',
            name='specialty',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='特长'),
        ),
    ]
